### ISSUE TITLE
A Big TODO

### ISSUE THREAD

**Issue by jasonjgardner** [jasonjgardner/jg-rtx#52]
### Textures Missing from JG RTX

> Thank you @erich666 for compiling this list!

- [ ] oak_sapling
- [ ] jungle_sapling
- [ ] spruce_sapling
- [ ] cactus_bottom
- [ ] birch_sapling
- [ ] piston_top_sticky
- [ ] piston_top
- [ ] piston_side
- [ ] piston_bottom
- [ ] piston_inner
- [ ] brewing_stand
- [ ] cocoa_stage2
- [ ] cocoa_stage1
- [ ] cocoa_stage0
- [ ] tripwire
- [ ] end_portal_frame_eye
- [ ] redstone_dust_dot
- [ ] pumpkin_stem
- [ ] attached_pumpkin_stem
- [ ] potatoes_stage0
- [ ] potatoes_stage1
- [ ] potatoes_stage2
- [ ] nether_wart_stage0
- [ ] nether_wart_stage1
- [ ] nether_wart_stage2
- [ ] beacon
- [ ] dropper_front
- [ ] dropper_front_vertical
- [ ] acacia_sapling
- [ ] dark_oak_sapling
- [ ] white_stained_glass_pane_top
- [ ] orange_stained_glass_pane_top
- [ ] magenta_stained_glass_pane_top
- [ ] light_blue_stained_glass_pane_top
- [ ] yellow_stained_glass_pane_top
- [ ] lime_stained_glass_pane_top
- [ ] pink_stained_glass_pane_top
- [ ] gray_stained_glass_pane_top
- [ ] light_gray_stained_glass_pane_top
- [ ] cyan_stained_glass_pane_top
- [ ] purple_stained_glass_pane_top
- [ ] blue_stained_glass_pane_top
- [ ] brown_stained_glass_pane_top
- [ ] green_stained_glass_pane_top
- [ ] red_stained_glass_pane_top
- [ ] black_stained_glass_pane_top
- [ ] chorus_plant
- [ ] chorus_flower
- [ ] chorus_flower_dead
- [x] command_block_conditional
- [ ] frosted_ice_0
- [ ] frosted_ice_1
- [ ] frosted_ice_2
- [ ] frosted_ice_3
- [ ] water_overlay
- [ ] redstone_dust_overlay
- [ ] white_shulker_box
- [ ] orange_shulker_box
- [ ] magenta_shulker_box
- [ ] light_blue_shulker_box
- [ ] yellow_shulker_box
- [ ] lime_shulker_box
- [ ] pink_shulker_box
- [ ] gray_shulker_box
- [ ] light_gray_shulker_box
- [ ] cyan_shulker_box
- [ ] purple_shulker_box
- [ ] blue_shulker_box
- [ ] brown_shulker_box
- [ ] green_shulker_box
- [ ] red_shulker_box
- [ ] black_shulker_box
- [ ] dried_kelp_bottom
- [ ] kelp
- [ ] kelp_plant
- [ ] sea_pickle
- [ ] tall_seagrass_bottom
- [ ] tall_seagrass_top
- [ ] dead_tube_coral_block
- [ ] dead_bubble_coral_block
- [ ] dead_fire_coral_block
- [ ] brain_coral
- [ ] fire_coral_fan
- [ ] horn_coral_fan
- [ ] dead_tube_coral_fan
- [ ] dead_brain_coral_fan
- [ ] dead_bubble_coral_fan
- [ ] dead_fire_coral_fan
- [ ] dead_horn_coral_fan
- [ ] turtle_egg
- [ ] turtle_egg_slightly_cracked
- [ ] turtle_egg_very_cracked
- [ ] conduit
- [ ] dead_brain_coral
- [ ] bamboo_singleleaf
- [ ] bamboo_stage0
- [ ] bell_top
- [ ] bell_side
- [ ] bell_bottom
- [ ] composter_compost
- [ ] composter_ready
- [ ] jigsaw_top
- [ ] jigsaw_bottom
- [ ] jigsaw_side
- [ ] loom_bottom
- [ ] stonecutter_top
- [ ] stonecutter_side
- [ ] stonecutter_bottom
- [ ] stonecutter_saw
- [ ] bee_nest_front_honey
- [ ] soul_campfire_fire
- [ ] soul_campfire_log_lit
- [ ] crimson_roots_pot
- [ ] warped_roots_pot
- [ ] respawn_anchor_top
- [ ] respawn_anchor_top_off
- [ ] respawn_anchor_side0
- [ ] respawn_anchor_side1
- [ ] respawn_anchor_side2
- [ ] respawn_anchor_side3
- [ ] respawn_anchor_side4
- [ ] respawn_anchor_bottom
- [ ] jigsaw_lock
- [ ] chain
- [ ] candle
- [ ] candle_lit
- [ ] white_candle
- [ ] orange_candle
- [ ] magenta_candle
- [ ] light_blue_candle
- [ ] yellow_candle
- [ ] lime_candle
- [ ] pink_candle
- [ ] gray_candle
- [ ] light_gray_candle
- [ ] cyan_candle
- [ ] purple_candle
- [ ] blue_candle
- [ ] brown_candle
- [ ] green_candle
- [ ] red_candle
- [ ] black_candle
- [ ] white_candle_lit
- [ ] orange_candle_lit
- [ ] magenta_candle_lit
- [ ] light_blue_candle_lit
- [ ] yellow_candle_lit
- [ ] lime_candle_lit
- [ ] pink_candle_lit
- [ ] gray_candle_lit
- [ ] light_gray_candle_lit
- [ ] cyan_candle_lit
- [ ] purple_candle_lit
- [ ] blue_candle_lit
- [ ] brown_candle_lit
- [ ] green_candle_lit
- [ ] red_candle_lit
- [ ] black_candle_lit
- [ ] lightning_rod_on
- [ ] spore_blossom
- [ ] spore_blossom_base
- [ ] potted_azalea_bush_top
- [ ] potted_flowering_azalea_bush_top
- [ ] potted_azalea_bush_side
- [ ] potted_flowering_azalea_bush_side
- [ ] potted_azalea_bush_plant
- [ ] potted_flowering_azalea_bush_plant
- [ ] small_dripleaf_top
- [ ] small_dripleaf_side
- [ ] small_dripleaf_stem_top
- [ ] small_dripleaf_stem_bottom
- [ ] powder_snow
- [ ] sculk_sensor_top
- [ ] sculk_sensor_side
- [ ] sculk_sensor_bottom
- [ ] sculk_sensor_tendril_active
- [ ] sculk_sensor_tendril_inactive

**Comment by erich666** [comment]
Ha, wow, that'll keep you busy for the winter. Honestly, I look forward to all additions! The new version of Houdini (19) is out and they're doing a nice job with converting Mineways USD materials to PBR materials in their system. Here's a (noisy - needs more rays) render of my little test scene
![H19_lights_karma](https://user-images.githubusercontent.com/803995/141477572-30b3ab6f-5759-4210-b511-ac113db832d9.jpg)
.
